package pt.diamondcars.dcbobackend.domain.client;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import pt.diamondcars.dcbobackend.support.AbstractPostgresIntegrationTest;

/**
 * {@code @DataJpaTest} for the {@link Client} aggregate: confirms it round-trips through the real
 * {@code clients} table (TASK-006 requirement 10) with {@code ddl-auto: validate} satisfied
 * (requirement 11).
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class ClientRepositoryTest extends AbstractPostgresIntegrationTest {

	@Autowired
	private ClientRepository clientRepository;

	/**
	 * Confirms a {@link Client} saved with only its required fields set can be reloaded with its
	 * database-matching default ({@code purchases_count = 0}) intact.
	 *
	 * <p>Uses {@code saveAndFlush}, not {@code save}: {@code createdAt}/{@code updatedAt} are
	 * generated by Hibernate right before the {@code INSERT} is sent, so without an explicit flush
	 * the assertions below would run against a still-pending, not-yet-inserted entity.
	 *
	 * @throws AssertionError if the reloaded client does not match what was saved
	 */
	@Test
	void savesAndReloadsAClientWithDefaults() {
		Client saved = clientRepository.saveAndFlush(
				Client.builder().name("Cliente Teste").phone("912345678").build());

		Client reloaded = clientRepository.findById(saved.getId()).orElseThrow();

		assertThat(reloaded.getName()).isEqualTo("Cliente Teste");
		assertThat(reloaded.getPhone()).isEqualTo("912345678");
		assertThat(reloaded.getPurchasesCount()).isZero();
		assertThat(reloaded.getCreatedAt()).isNotNull();
		assertThat(reloaded.getUpdatedAt()).isNotNull();
	}
}
