package pt.diamondcars.dcbobackend.domain.partner;

import static org.assertj.core.api.Assertions.assertThat;

import java.math.BigDecimal;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import pt.diamondcars.dcbobackend.support.AbstractPostgresIntegrationTest;

/**
 * {@code @DataJpaTest} for the {@link Partner} aggregate: confirms it round-trips through the real
 * {@code partners} table (TASK-006 requirement 10) with {@code ddl-auto: validate} satisfied
 * (requirement 11) and its declared defaults applied.
 *
 * <p>Extends {@link AbstractPostgresIntegrationTest} so the datasource is the shared Testcontainers
 * Postgres, not an in-memory database; {@link AutoConfigureTestDatabase.Replace#NONE} stops Spring
 * Boot from trying to substitute an embedded database instead. Each {@code @Test} runs inside a
 * transaction that {@code @DataJpaTest} rolls back automatically, so no cleanup code is needed
 * despite the container being a JVM-wide singleton shared with every other test class.
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class PartnerRepositoryTest extends AbstractPostgresIntegrationTest {

	@Autowired
	private PartnerRepository partnerRepository;

	/**
	 * Confirms a {@link Partner} saved with only its required field set can be reloaded with its
	 * database-matching defaults ({@code cars_count = 0}, {@code total_commission = 0.00}) intact.
	 *
	 * <p>Uses {@code saveAndFlush}, not {@code save}: {@code createdAt}/{@code updatedAt} are
	 * generated by Hibernate right before the {@code INSERT} is sent, so without an explicit flush
	 * the assertions below would run against a still-pending, not-yet-inserted entity.
	 *
	 * @throws AssertionError if the reloaded partner does not match what was saved
	 */
	@Test
	void savesAndReloadsAPartnerWithDefaults() {
		Partner saved = partnerRepository.saveAndFlush(Partner.builder().name("Auto Silva").build());

		Partner reloaded = partnerRepository.findById(saved.getId()).orElseThrow();

		assertThat(reloaded.getName()).isEqualTo("Auto Silva");
		assertThat(reloaded.getCarsCount()).isZero();
		assertThat(reloaded.getTotalCommission()).isEqualByComparingTo(BigDecimal.ZERO);
		assertThat(reloaded.getCreatedAt()).isNotNull();
		assertThat(reloaded.getUpdatedAt()).isNotNull();
	}
}
