package pt.diamondcars.dcbobackend.domain.notification;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import pt.diamondcars.dcbobackend.support.AbstractPostgresIntegrationTest;

/**
 * {@code @DataJpaTest} for the {@link Notification} aggregate: confirms it round-trips through the
 * real {@code notifications} table (TASK-006 requirement 10), including that it has no {@code
 * updated_at} column (only {@code created_at} auditing, per {@code V1__init.sql:126-135}).
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class NotificationRepositoryTest extends AbstractPostgresIntegrationTest {

	@Autowired
	private NotificationRepository notificationRepository;

	/**
	 * Confirms a {@link Notification} saved with only its required fields set can be reloaded with
	 * its database-matching default ({@code read = false}) intact, and that {@code createdAt} is
	 * populated without any {@code updatedAt} field existing on the entity.
	 *
	 * <p>Uses {@code saveAndFlush}, not {@code save}: {@code createdAt} is generated by Hibernate
	 * right before the {@code INSERT} is sent, so without an explicit flush the assertion below
	 * would run against a still-pending, not-yet-inserted entity.
	 *
	 * @throws AssertionError if the reloaded notification does not match what was saved
	 */
	@Test
	void savesAndReloadsANotificationWithDefaults() {
		Notification saved = notificationRepository.saveAndFlush(
				Notification.builder().tipo("follow_up").mensagem("Follow-up agendado").build());

		Notification reloaded = notificationRepository.findById(saved.getId()).orElseThrow();

		assertThat(reloaded.getTipo()).isEqualTo("follow_up");
		assertThat(reloaded.getMensagem()).isEqualTo("Follow-up agendado");
		assertThat(reloaded.isRead()).isFalse();
		assertThat(reloaded.getCreatedAt()).isNotNull();
	}
}
