package pt.diamondcars.dcbobackend.domain.support;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.UUID;
import lombok.Getter;
import org.hibernate.Hibernate;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UuidGenerator;

/**
 * Base mapped superclass for every JPA entity in the back-office domain model.
 *
 * <p>Centralises the two concerns that must behave identically across all eight entities mapped
 * over {@code V1__init.sql}: primary-key generation and creation-timestamp auditing.
 *
 * <ul>
 *   <li>{@code id} is generated by Hibernate ({@link UuidGenerator}) as a random {@link UUID},
 *       matching the {@code UUID PRIMARY KEY DEFAULT gen_random_uuid()} convention shared by every
 *       table in the schema.</li>
 *   <li>{@code createdAt} is populated exclusively by Hibernate's {@link CreationTimestamp} — no
 *       entity or service sets it by hand (TASK-006 requirement 6).</li>
 *   <li>{@link #equals(Object)}/{@link #hashCode()} are identity-based on {@code id}, deliberately
 *       avoiding Lombok's {@code @Data}/{@code @EqualsAndHashCode} (TASK-006 requirement 2), which
 *       would pull in mutable/collection fields and break entity semantics inside Hibernate-managed
 *       collections and hash-based containers.</li>
 * </ul>
 */
@Getter
@MappedSuperclass
public abstract class AbstractDomainEntity {

	@Id
	@UuidGenerator
	@Column(name = "id", nullable = false, updatable = false)
	private UUID id;

	@CreationTimestamp
	@Column(name = "created_at", nullable = false, updatable = false)
	private OffsetDateTime createdAt;

	/**
	 * Compares entities by identity (persistent {@code id}), the only correct notion of equality
	 * for a JPA entity: two managed instances represent the same row if and only if their ids
	 * match, regardless of which mutable fields happen to be loaded or changed. An entity without
	 * an id yet (transient, not yet persisted) is never equal to any other instance, since a
	 * transient entity has no stable identity.
	 *
	 * @param other the object to compare against
	 * @return {@code true} if {@code other} is a persisted entity of the same runtime type with the
	 *         same {@code id}
	 */
	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (other == null || Hibernate.getClass(this) != Hibernate.getClass(other)) {
			return false;
		}
		AbstractDomainEntity that = (AbstractDomainEntity) other;
		return id != null && Objects.equals(id, that.getId());
	}

	/**
	 * Returns a constant hash code for the runtime entity type.
	 *
	 * <p>Deliberately does not hash {@code id} (which is {@code null} until the entity is first
	 * persisted): an entity's hash code must never change over its lifetime, including the moment
	 * it transitions from transient to persistent, or it would violate the hash code contract while
	 * sitting inside a {@link java.util.HashSet}/{@link java.util.HashMap}.
	 *
	 * @return a hash code stable across the entity's entire lifecycle
	 */
	@Override
	public int hashCode() {
		return Hibernate.getClass(this).hashCode();
	}
}
